// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PeluqueriaBack.Data.Models;

public partial class Turno
{
    public int Id { get; set; }

    public DateOnly? Fecha { get; set; }

    public string Hora { get; set; }

    public string Cliente { get; set; }

    public DateOnly? FechaCancelacion { get; set; }

    public string MotivoCancelacion { get; set; }

    public virtual ICollection<DetallesTurno> DetallesTurnos { get; set; } = new List<DetallesTurno>();
}