// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TiendaAPI.Data.Models;

public partial class Producto
{
    public int ProductoId { get; set; }

    public string Nombre { get; set; }

    public int CategoriaId { get; set; }

    public decimal Precio { get; set; }

    public int Stock { get; set; }

    public DateTime FechaDeIngreso { get; set; }

    public virtual Categorium Categoria { get; set; }
}