// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LibrosPParcial.Data.Models;

public partial class Libro
{
    public int LibroId { get; set; }

    public string Titulo { get; set; }

    public string Autor { get; set; }

    public int CategoriaId { get; set; }

    public DateTime FechaPublicacion { get; set; }

    public bool Disponible { get; set; }

    public virtual Categoria Categoria { get; set; }
}